default:
 attributes:
  GENERIC_MAX_HEALTH: 20
  GENERIC_LUCK: 0
  GENERIC_KNOCKBACK_RESISTANCE: 0
  GENERIC_MOVEMENT_SPEED: 0.1
  GENERIC_ATTACK_DAMAGE: 2
  GENERIC_ARMOR: 0
  GENERIC_ARMOR_TOUGHNESS: 0
  GENERIC_ATTACK_SPEED: 4
groups:
 glassy: 1
  attributes:
   GENERIC_MAX_HEALTH: 4
   GENERIC_ATTACK_DAMAGE: 10
 heavyarmor: 2
  attributes:
   GENERIC_ARMOR: 30
   GENERIC_ARMOR_TOUGHNESS: 20
   GENERIC_KNOCKBACK_RESISTANCE: 1
   GENERIC_MOVEMENT_SPEED: 0.025
   GENERIC_ATTACK_SPEED: 3
 luckless: 3
  attributes:
   GENERIC_LUCK: -3
 lucker: 4
  attributes:
   GENERIC_LUCK: 3
 immovable: 5
  attributes:
   GENERIC_MOVEMENT_SPEED: 0
   GENERIC_ATTACK_SPEED: 0
   GENERIC_KNOCKBACK_RESISTANCE: 1
 flash: 6
  attributes:
   GENERIC_MOVEMENT_SPEED: 1
   GENERIC_ATTACK_SPEED: 10
 weak: 7
  attributes:
   GENERIC_ATTACK_SPEED: 16
   GENERIC_ATTACK_DAMAGE: 0.25
 strong: 8
  attributes:
   GENERIC_ATTACK_SPEED: 1
   GENERIC_ATTACK_DAMAGE: 8
 pusher: 9
  attributes:
   GENERIC_ATTACK_KNOCKBACK: 5
 healthy: A
  attributes:
   GENERIC_MAX_HEALTH: 29
