attributes:
 big_boost: 03
  GENERIC_MAX_HEALTH: 40
  GENERIC_LUCK: 0
  GENERIC_KNOCKBACK_RESISTANCE: 0.6
  GENERIC_MOVEMENT_SPEED: 0.15
  GENERIC_ATTACK_DAMAGE: 5
  GENERIC_ARMOR: 8
  GENERIC_ARMOR_TOUGHNESS: 4
  GENERIC_ATTACK_SPEED: 5
 medium_boost: 02
  GENERIC_MAX_HEALTH: 30
  GENERIC_LUCK: 2
  GENERIC_KNOCKBACK_RESISTANCE: 0.2
  GENERIC_MOVEMENT_SPEED: 0.13
  GENERIC_ATTACK_DAMAGE: 4
  GENERIC_ARMOR: 4
  GENERIC_ARMOR_TOUGHNESS: 2
  GENERIC_ATTACK_SPEED: 4.5
 small_boost: 01
  GENERIC_MAX_HEALTH: 24
  GENERIC_LUCK: 1
  GENERIC_KNOCKBACK_RESISTANCE: 0.1
  GENERIC_MOVEMENT_SPEED: 0.11
  GENERIC_ATTACK_DAMAGE: 3
  GENERIC_ARMOR: 2
  GENERIC_ARMOR_TOUGHNESS: 1
  GENERIC_ATTACK_SPEED: 4.1
 default:
  GENERIC_MAX_HEALTH: 20
  GENERIC_LUCK: 0
  GENERIC_KNOCKBACK_RESISTANCE: 0
  GENERIC_MOVEMENT_SPEED: 0.1
  GENERIC_ATTACK_DAMAGE: 2
  GENERIC_ARMOR: 0
  GENERIC_ARMOR_TOUGHNESS: 0
  GENERIC_ATTACK_SPEED: 4
